### ISSUE TITLE
Running Problem

### ISSUE THREAD

**Issue by EyupCanARSLAN** [BitOfUniverse/kurento-one2many-with-rooms#1]
Hi, 

I look at this tutorial and decided to run on my local machine via VMvare on Ubuntu Server 14.04 TLS

Before start to run this, 
I install KMS 6 on ubuntu via this referance page.
http://doc-kurento.readthedocs.io/en/stable/installation_guide.html#migrating-from-kms-v5-to-v6

After KMS install, I follow the this link at below as referance
http://doc-kurento.readthedocs.io/en/stable/tutorials/node/tutorial-one2many.html

My installation step for this link a little different

Here is the my installation steps:

```
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y nodejs
sudo npm install -g bower

```

After this step

I follow these

```
git clone https://github.com/BitOfUniverse/kurento-one2many-with-rooms.git
cd kurento-tutorial-node/kurento-one2many-call
git checkout 6.6.0
npm install


```

 At there I used your git adress: **git clone https://github.com/BitOfUniverse/kurento-one2many-with-rooms.git**

Until these steps everthing looks fine. But when I run this command

**npm start**

I get the following error on log file 

> 
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
> 2 info using npm@2.15.1
> 3 info using node@v0.10.48
> 4 verbose node symlink /usr/bin/node
> 5 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 6 info prestart kurento-one2many-call@6.2.2-dev
> 7 info start kurento-one2many-call@6.2.2-dev
> 8 verbose unsafe-perm in lifecycle true
> 9 info kurento-one2many-call@6.2.2-dev Failed to exec start script
> 10 verbose stack Error: kurento-one2many-call@6.2.2-dev start: `node server.js`
> 10 verbose stack Exit status 8
> 10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
> 10 verbose stack     at EventEmitter.emit (events.js:98:17)
> 10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 10 verbose stack     at ChildProcess.emit (events.js:98:17)
> 10 verbose stack     at maybeClose (child_process.js:766:16)
> 10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
> 11 verbose pkgid kurento-one2many-call@6.2.2-dev
> 12 verbose cwd /home/can/kurento-one2many-with-rooms
> 13 error Linux 4.4.0-31-generic
> 14 error argv "/usr/bin/node" "/usr/bin/npm" "start"
> 15 error node v0.10.48
> 16 error npm  v2.15.1
> 17 error code ELIFECYCLE
> 18 error kurento-one2many-call@6.2.2-dev start: `node server.js`
> 18 error Exit status 8
> 19 error Failed at the kurento-one2many-call@6.2.2-dev start script 'node server.js'.
> 19 error This is most likely a problem with the kurento-one2many-call package,
> 19 error not with npm itself.
> 19 error Tell the author that this fails on your system:
> 19 error     node server.js
> 19 error You can get information on how to open an issue for this project with:
> 19 error     npm bugs kurento-one2many-call
> 19 error Or if that isn't available, you can get their info via:
> 19 error
> 19 error     npm owner ls kurento-one2many-call
> 19 error There is likely additional logging output above.
> 20 verbose exit [ 1, true ]

My question is that, What Am I wrong? When I try to run example on Kurento, there isn't any error. But at there I get these error.

Also, I try to install socket.Io and etc. when I get error, but not solve my problem.

I found on the internet that 8080 port problem and kill apps on this port on cmd  but still I have error.

What can I do? If you help me, I will be very happy.

Thaks a lot of your answer, have a nice and hapy day  :) :) :) 

Best Rigards

**Comment by Xaqron** [comment]
@eyup2 I have created a bug-fixed fork and submitted a pull request.
